"use client";
import Header from "@/components/Header";
import { Instrument_Sans, Space_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import WalletContextProvider from "./components/WalletContextProvider";

import "./globals.css";
const spaceMono = Space_Mono({ weight: ["400", "700"], subsets: ["latin"] });
const instrumentSans = Instrument_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "wagmi.quest",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="wagmi">
      {
        // .in-s {
        //   font-family: ${instrumentSans.style.fontFamily};
        //   font-style: ${instrumentSans.style.fontStyle};
        // }
      }
      <style>{`
        .sp-m {
          font-family: ${spaceMono.style.fontFamily};
          font-weight: ${spaceMono.style.fontWeight};
        }
      `}</style>
      <body className={spaceMono.className}>
        <Toaster />
        <WalletContextProvider>
          {children}
          <Header />
        </WalletContextProvider>
      </body>
    </html>
  );
}
